// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

const SUPABASE_URL = "https://oqvvxnxbkdynmmsokzda.supabase.co";
const SUPABASE_PUBLISHABLE_KEY =
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9xdnZ4bnhia2R5bm1tc29remRhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI5MjI0MjIsImV4cCI6MjA2ODQ5ODQyMn0.CvVv_987QSzlFMi34IPhg0QXqXfVBk-aOBJrHbZvyDM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL,
  SUPABASE_PUBLISHABLE_KEY
);
